### PR TITLE
Fixed TypeScript bindings for nonshrink

### PR DESCRIPTION
**Pull request by CaptJakk**
changed typescript bindings to correct nonShrink to nonshrink, tests demonstrating them from within typescript are included

### CODE REVIEW

**Comment by CaptJakk** [comment]
It's not clear to me what is actually failing on this build. When I look at the travisCI output it looks like all of the tests are passing. The only things that look like they are failing is that mocha is under versioned, as well as something about 'david'. Any idea what that is?

**Comment by CaptJakk** [comment]
So it looks like david was the one complaining about mocha. I've updated the version to what david requested. We'll see if travis passes the build.

**Comment by phadej** [comment]
Thanks!

**Comment by CaptJakk** [comment]
:v:

**Pull request merged**
