### PR TITLE
152

### PR DESCRIPTION
**Pull request by techtangents**
Fix for #152 and #153. 

Includes commit for #153 as I was unable to successfully build the project without it.

### CODE REVIEW

**Comment by phadej** [comment]
I'll try to check this PR still this week. Thanks for patience.

**Comment by markalfred** [comment]
This looks awesome, thanks @techtangents 🙌

**Comment by techtangents** [comment]
Would you like me to rebase to fix the conflicts?

**Comment by phadej** [comment]
rebase would be great!

**Comment by phadej** [comment]
rebased myself

**Pull request closed without merging**
