### PR TITLE
[WIP] Add typescript type definition

### PR DESCRIPTION
**Pull request by jvanbruegge**

### CODE REVIEW

**Comment by phadej** [comment]
Looks great, just had discussion about having type-definitions last week! Is it easy to add a test testing at least some of those definitions as part of the test-suite, i.e. having type-script test-suite as well?

**Comment by phadej** [comment]
I updated `david`, if you rebase, travis should be green.

**Comment by jvanbruegge** [comment]
Yes, you can write a normal test file in typescript and check if it compiles

**Comment by jvanbruegge** [comment]
The problem I have here is with the vararg fubctiobs, as typescriot only allows the vararg to be the last parameter. So some of the functions I cant type at all

**Comment by phadej** [comment]
Will they be typeable if we provide a versions with varargs as the the last parameters? `.combine` has quite advanced type, after all?

**Comment by jvanbruegge** [comment]
Yes, the vararg has to be the last one and there shouldnt be an optional argument too

**Comment by jvanbruegge** [comment]
Thats the problem with forall too, the optional parameter is not the last one

**Comment by phadej** [comment]
can typescript express dependencies, like `tsCombine(f : (a, b ...) => r, x : generator<a>, y : generator<b> ...)`?

We could add `tsForall`, and `tsCombine` if they are even somehow typeable in TypeScript

**Comment by jvanbruegge** [comment]
Sadly not yet. I can only type it:
`
tsCombine(f : (a, ...any[]) => r, x1 : generator<a>, ...xn : generator<any>)`
So you get types for the first generator and an any type for the rest.

But typescript allows polymorphic type declarations, so you can just copy & paste this until 10 params (most people use less) and have the any vararg declaration for the rare occasions you use more

**Comment by jvanbruegge** [comment]
Ok, I think I got it mostly
The stuff missing is:
- the either stuff, because I dont know how it should be used or how it is useful
- the fn/fun arbitrary, as I dont know how to use them (where does the b type come from?)

**Comment by jvanbruegge** [comment]
I think we dont need extra typescript functions. The way this is here now should be sufficient

**Comment by phadej** [comment]
`b` in `fn` can be anything, we don't need to generate the values of that type, we just test them for an equality (iirc with `===`)

**Comment by jvanbruegge** [comment]
yeah, but the function that is generated, what does it accept?

**Comment by phadej** [comment]
`either` is a special case of `sum` (which you type very loosely).

The noteable thing here, is that `either` and `sum` are **tagged**, i.e. in `either int int` scenario, you'll know whether you have *left* or *right* `int`. IIRC there was issue about producing untagged unions too, but there the problem is with shrinking.

**Comment by phadej** [comment]
it accepts values of `b`, i.e. anything you want.

**Comment by jvanbruegge** [comment]
Ahh, ok. And what is the difference between `fn` and `fun`?

**Comment by jvanbruegge** [comment]
I think that most of the use cases are now covered, the either stuff can be added later on if there is demand for it

**Comment by phadej** [comment]
Merged as a part of https://github.com/jsverify/jsverify/pull/202

**Pull request closed without merging**
